### ISSUE TITLE
Question about k means

### ISSUE THREAD

**Issue by tombisho** [isglobal-brge/dsMLClient#2]
Hi, I really like all these new functions and look forward to seeing them being used in some research.

I was trying to understand the k means function. My concern was that if a user could specify k to be the same as the number of points in a study, and you ran the function with that study, the centroids would just take the values of the points. In that way a user could get all the data.

Maybe I misunderstood how it works, but maybe there needs to be some kind of disclosure control to limit k relative to the number of rows in the data frame?

Thanks

Tom

**Comment by tombisho** [comment]
Great work! I can see the changes and I agree that should fix it. Thank you.

BTW I am going to use this function as an example of the recent increases in analysis possibilities in DataSHIELD for a talk I will be giving next month.

**Comment by isglobal-brge** [comment]
Thank you Tom, 

Could you, please, share with us the presentation?
